### ISSUE TITLE
redirect to another page after signup/login

### ISSUE THREAD

**Issue by datnguyenzzz** [bmstu-iu9/utp2019-9-forum#4]

**Comment by Mazdaywik** [comment]
А где код-то? Задачу нужно закрывать после того, как код, её решающий, попал в репозиторий. Причём в ветку `master`.

**Comment by datnguyenzzz** [comment]
> А где код-то? Задачу нужно закрывать после того, как код, её решающий, попал в репозиторий. Причём в ветку `master`.

да задача выполнена. сейчас все в репозитории develop . после всего я буду сливать develop в master

**Comment by Mazdaywik** [comment]
А, прошу прощения, ветку `develop` не заметил. Можно в описаниях коммитов добавлять `#4`, тогда они будут привязываться к задаче. Будет видна постановка задачи, коммит, коммит, коммит, задача закрыта.

Номера лучше не торопиться вешать только в одном случае: когда историю планируется переписывать. Например, переупорядочивать или объединять коммиты. Но если планируется переписать историю, то это значит, что задача не завершена ещё, т.е. автор свои коммиты осознаёт как незавершённые и планирует ещё дорабатывать.
